# Generated by Django 5.0.2 on 2024-02-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('ConcesionarioId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('VehiculoID', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Anio', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('TransaccionId', models.AutoField(primary_key=True, serialize=False)),
                ('FechaVenta', models.DateField()),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebatecnica.cliente')),
                ('ConcesionarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebatecnica.concesionario')),
                ('VehiculoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebatecnica.vehiculo')),
            ],
        ),
    ]
